config/routes.rb
Rails.application.routes.draw do
  root to: 'companies#index'
  resources :companies do
    resources :salesmen, only: [:index, :destroy, :create]
    resources :goals, only: [:new, :destroy, :create, :show] do
      resources :days, only: [:show, :edit, :update]
    end
  end
  devise_for :owners, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_navbar.html.erb
<div class="navbar-fixed">
  <nav class="top-nav">
    <div class="nav-wrapper col s12">
      <a href="/" class="brand-logo">
        <i class="material-icons">assistant_photo</i>Desafio Indeva</a>
      <a href="#" data-activates="side-bar" class="button-collapse">
        <i class="material-icons">menu</i>
      </a>

      <ul class="right hide-on-med-and-down">
        <% if current_owner %>
        <li>
          <a href="/owners/edit">Profile</a>
        </li>
        <li>
          <a href="#" class='dropdown-button' data-activates='companies' data-beloworigin="true" alignment='left'>My companies<i class="material-icons right">arrow_drop_down</i>
          </a>
          <ul id="companies" class="dropdown-content">
            <% current_owner.my_companies.each do |company| %>
            <li>
              <a href="/companies/<%= company.id %>"><%= company.name %></a>
            </li>
            <li class="divider"></li>
            <% end %>
            <li>
              <a class="" href="/companies/new">+ Add company</a>
            </li>
          </ul>
        </li>
        <li>
          <%= link_to('Logout', destroy_owner_session_path, :method => :delete) %></li>
      <% else %>
        <li>
          <a href="/owners/sign_in">Login</a>
        </li>
        <li>
          <a href="/owners/sign_up">Sign Up</a>
        </li>
        <% end %>
      </ul>
    </div>
  </nav>
</div>

app/views/shared/_sidebar.html.erb
<ul class="side-nav" id="side-bar">
  <% if current_owner %>
  <li>
    <a href="/users/edit">Profile</a>
  </li>
  <li>
    <div class="divider"></div>
  </li>
  <li>
    <a href="#" class='dropdown-button' data-activates='companies_side' data-beloworigin="true" alignment='left'>My companies<i class="material-icons right">arrow_drop_down</i>
    </a>
    <ul id="companies_side" class="dropdown-content">
      <% current_owner.my_companies.each do |company| %>
      <li>
        <a href="/<%= company.name %>"><%= company.name %></a>
      </li>
      <li class="divider"></li>
      <% end %>
      <li>
        <a class="" href="#add_company_modal">+ Add company</a>
      </li>
    </ul>
  </li>
  <li>
    <%= link_to('Logout', destroy_owner_session_path, :method => :delete) %></li>
<% else %>
  <li>
    <a href="/users/sign_in">Login</a>
  </li>
  <li>
    <div class="divider"></div>
  </li>
  <li>
    <a href="/users/sign_up">Sign Up</a>
  </li>
  <li>
    <div class="divider"></div>
  </li>
  <% end %>
</ul>

app/views/shared/_sidebar2.html.erb
<ul class="side-nav fixed side-nav-goal" id="side-bar-goal">
  <li>
    <div>
      <span class="company_title">
        <a href="/companies/<%= @company.id %>"><%= @company.name.truncate(6) %></a>
      </span>
      <a class="company_icon right">
        <i class="material-icons">
          <%= link_to 'edit', edit_company_path(@company.id) %>
        </i>
      </a>

      <a class="company_icon right">
        <i class="material-icons">
          <%= link_to 'delete',company_path(@company.id),
            method: :delete,
            data: { confirm: 'Are you sure?' } %>
        </i>
      </a>
    </div>
  </li>
  <li>
    <div class="divider"></div>
  </li>
  <li class="">
    <!-- <span class="goal_title">goals</span> -->
    <ul class="collapsible" data-collapsible="accordion">
      <li>
        <div class="collapsible-header">
          <i class="material-icons">list</i>Goals</div>
        <div class="collapsible-body list">
          <span>
            <ul class="goals">
              <% @company.goal.each do |goal| %>
              <li class="goal_<%= goal.id %>">
                <div>
                  <a href="/companies/<%= @company.id %>/goals/<%= goal.id %>" class="open_goal">
                    <span><%= goal.name.truncate(6) %></span>
                  </a>
                  <a class="right remove_goal" href="#" id="<%= goal.id %>">
                    <i class="material-icons" id="<%= goal.id %>">
                      <%= link_to 'delete', company_goal_path(:company_id => @company.id, :id => goal.id),
                             method: :delete, data: { confirm: 'Are you sure?' } %></i>
                  </a>
                </div>
              </li>
              <% end %>
              <li>
                <div class="center">
                  <span>
                    <td><%= link_to 'New Goal', new_company_goal_path(@company.id), class:"center btn" %></td>
                  </span>
                </div>
              </li>
            </ul>
          </span>
        </div>
      </li>
      <li>
        <div class="divider"></div>
      </li>

      <ul class="collapsible" data-collapsible="accordion">
        <li>
          <div class="collapsible-header">
            <i class="material-icons">list</i>
            <a href="/companies/<%= @company.id %>/salesmen">Salesmen</a>
          </div>
        </li>
      </ul>
  </ul>
</li>
<li>
  <div class="divider"></div>
</li>
</ul>

<div class="fixed-action-btn horizontal hide-on-med-and-up">
<a href="#" data-activates="side-bar-goal" class="button-collapse btn-floating btn-large waves-effect waves-light grey bottom">
  <i class="material-icons">menu</i>
</a>
</div>