config/routes.rb
Rails.application.routes.draw do
  root to: 'companies#index'
  resources :companies do
    resources :salesmen, only: [:index, :destroy, :create]
    resources :goals, only: [:new, :destroy, :create, :show] do
      resources :days, only: [:show, :edit, :update]
    end
  end
  devise_for :owners, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/day.rb
class Day < ApplicationRecord
  belongs_to :goal
  has_many :day_salesmen, dependent: :destroy
  has_many :salesmen, through: :day_salesmen
  validates_presence_of :date_day, :goal_id

  accepts_nested_attributes_for :day_salesmen
end

app/controllers/days_controller.rb
class DaysController < ApplicationController
  before_action :find_day, only: [:show, :edit, :update]
  before_action :find_company, only: [:show, :edit]

  def index
    @day = current_owner.companies.find(params[:company_id]).goal.find(params[:goal_id]).days
  end

  def show
    @salesmen = @day.salesmen.pluck(:name)
    @salesmencount = @salesmen.count
    if @salesmencount > 0
      @valuesalesmen = @day.value.to_f/(@salesmencount)
    end
  end

  def edit
    @dayup = Day.new
    @day_salesmen = @dayup.day_salesmen.build
    @salesman = @day_salesmen.build_salesman
  end

  def update
    if @day.update(params_day)
      flash[:notice] = "Day updated!"
      redirect_to edit_company_goal_day_path(:goal_id => params[:goal_id], :id => params[:id])
    else
      flash[:error] = "Could not update day!"
      redirect_to edit_company_goal_day_path(:goal_id => params[:goal_id], :id => params[:id])
    end
  end

  private

  def find_company
    @company = Company.find(params[:company_id])
  end

  def find_day
    @day = Day.find(params[:id])
  end

  def params_day
    params.require(:day).permit(:value, salesman_attributes:[:id, :name]).merge(goal_id: params[:goal_id])
  end
end

app/helpers/days_helper.rb
module DaysHelper
end

app/views/days/edit.html.erb
<%= render "shared/sidebar2" %>
<div class="container">
  <div class="row">
    <div class="col s10 offset-s2">
      <div class="row">
        <h4>Edit day</h4>
        <%= form_for @day, url: {action: "update"} do |f| %>
          <%= f.label :value_of_day %>
          <%= f.number_field :value, :step => 0.01 %>
          <%= f.submit "Update value", class:"center btn" %>
        <% end %>
        <%= form_for(@dayup, url: company_salesmen_path, method: :post) do |a| %>
          <%= a.hidden_field :day_id, :value => @day.id %>
          <%= a.hidden_field :goal_id, :value => @day.goal_id %>
          <%= a.fields_for :day_salesman do |aa| %>
            <%= a.fields_for :salesman do |aaa| %>
              <%= aaa.label :name_of_salesman %>
              <%= aaa.text_field :name %>
            <% end %>
          <% end %>
          <%= a.submit "Create one salesman", class:"center btn" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/days/show.html.erb
<%= render "shared/sidebar2" %>
<div class="container">
  <div class="row">
    <div class="col s10 offset-s2">
      <ul class="collection">
        <li class="collection-header">
          <h5>See details:</h5>
        </li>
        <li class="collection-item">Day:
          <%= @day.date_day.strftime("%d/%m/%y") %></li>
        <li class="collection-item">Total value:
          <% if @day.value != nil %>
            <%= @day.value %>
          <% else %>
            <%= link_to "Update the value getting on day", edit_company_goal_day_path %>
          <%end%>
        </li>
        <li class="collection-item">Value by Salesman:
            <% @salesmen.each do |salesman| %>
              <%= salesman %> => $<%= @valuesalesmen %>,
            <%end%>
        </li>
      </ul>
    </div>
  </div>
</div>