config/routes.rb
Rails.application.routes.draw do
  root to: 'companies#index'
  resources :companies do
    resources :salesmen, only: [:index, :destroy, :create]
    resources :goals, only: [:new, :destroy, :create, :show] do
      resources :days, only: [:show, :edit, :update]
    end
  end
  devise_for :owners, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/goal.rb
class Goal < ApplicationRecord
  belongs_to :company
  has_many :days, dependent: :destroy
  has_many :goal_salesmen, dependent: :destroy
  has_many :salesmen, through: :goal_salesmen

  validates_presence_of :date_start, :date_end, :name, :totalvalue
  validates_uniqueness_of :date_start, :date_end, scope: :company_id
  validate :end_date_is_after_start_date

  after_save :create_days

  def create_days
    rangeDate = (self.date_start..self.date_end).to_a
    rangeDate.each do |date|
      self.days << Day.create(date_day: date, goal_id: self.id )
    end
  end

private

  def end_date_is_after_start_date
    if date_end < date_start
      errors.add(:date_end, "Data of end cannot be less than the data of start!")
    end
  end

end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :find_goals, only: [:show, :edit, :update, :destroy]
  before_action :find_company, only: [:show, :new, :edit]

  def index
    @goal = current_owner.companies.find(params[:company_id]).goal
  end

  def new
    @goal = Goal.new
  end

  def show
    @goalcompanyid = @goal.company_id
    @date = Day.where(goal_id: params[:id]).pluck(:date_day, :id)
    @valueofalldays = @goal.days.where(goal_id: @goal.id).pluck(:value)
  end

  def create
    @goal = Goal.new(params_goal)
    if @goal.save
      @company = @goal.company
      flash[:notice] = "Goal created!"
      redirect_to company_path(:id => @company.id)
    else
      flash[:error] = "Could not create goal!"
      render :new
    end
  end

  def destroy
    @days = Day.find_by(goal_id: @goal.id)
    @days.destroy
    @goal.destroy
    @company = @goal.company
    flash[:notice] = "Goal deleted!"
    redirect_to company_path(:id => @company.id)
  end

  private

  def find_company
    @company = Company.find(params[:company_id])
  end

  def find_goals
    @goal = Goal.find(params[:id])
  end

  def params_goal
    params.require(:goal).permit(:name, :totalvalue, :date_start, :date_end, :month).merge(company_id: params[:company_id])
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/views/goals/new.html.erb
<%= render "shared/sidebar2" %>
<div class="container">
  <div class="row">
    <div class="col s10 offset-s2">
      <h4>Create new goal</h4>
      <%= form_for @goal, url: {action: "create"}, html: {class: "col s12" } do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
      <%= f.label :Date_Start %>
      <%= f.date_field :date_start %>
      <%= f.label :Date_End %>
      <%= f.date_field :date_end %>
      <%= f.label :totalvalue %>
      <%= f.number_field :totalvalue, :step => 0.01 %>
      <%= f.submit "Create", class:"center btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/goals/show.html.erb
<%= render "shared/sidebar2" %>
<div class="container">
  <div class="row">
    <div class="col s10 offset-s2">
      <div class="card">
        <div class="card-content"></div>
        <div class="card-tabs">
          <ul class="tabs tabs-fixed-width">
            <li class="tab">
              <a class="active" href="#test4">Show goal
                <%= @goal.name %>
              </a>
            </li>
            <li class="tab">
              <a href="#test5">Edit days of goal</a>
            </li>
            <li class="tab">
              <a href="#test6">Show days of goal</a>
            </li>
          </ul>
        </div>
        <div class="card-content grey lighten-4">
          <div id="test4">
            <ul class="collection">
              <li class="collection-header">
                <h5>See details:</h5>
              </li>
              <li class="collection-item">Name:
                <%= @goal.name %></li>
              <li class="collection-item">Date Start:
                <%= @goal.date_start %></li>
              <li class="collection-item">Date End:
                <%= @goal.date_end %></li>
              <li class="collection-item">Value of goal:
                <%= @goal.totalvalue %></li>
            </ul>
            <div class="fixed-action-btn horizontal click-to-toggle">
              <a class="btn-floating btn-large red">
                <i class="material-icons">menu</i>
              </a>
              <ul>
                <li>
                  <a class="btn-floating blue darken-1" href="/companies/<%= @goalcompanyid %>/goals/new">
                    <i class="material-icons">add_circle</i>
                  </a>
                </li>
                <li>
                  <a class="btn-floating green">
                    <i class="material-icons">
                      <%= link_to 'delete', company_goal_path(:company_id => @goalcompanyid, :id => @goal.id),
                    method: :delete, data: { confirm: 'Are you sure?' } %></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div id="test5">
            <% @date.each do |datedays| %>
            <div class="collection">
              <span class="collection-item"><%= link_to datedays.first.strftime("%d/%m/%y"), edit_company_goal_day_path(:company_id => @goalcompanyid, :goal_id => @goal.id, :id => datedays.last) %></span>
            </div>
            <%end%>
          </div>
          <div id="test6">
            <% @date.each do |datedays| %>
            <div class="collection">
              <span class="collection-item"><%= link_to datedays.first.strftime("%d/%m/%y"), company_goal_day_path(:company_id => @goalcompanyid, :goal_id => @goal.id, :id => datedays.last) %></span>
            </div>
            <%end%>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>